name: Setup Python
description: Setup Python with pipx (for act)

inputs:
  python-version:
    required: true

runs:
  using: "composite"
  steps:
    - uses: actions/setup-python@v4
      with:
        python-version: ${{ inputs.python-version }}

    - name: Validate python
      # setup-python will not check for installation
      # if manifest was not found (network error)
      run: |
        import sys, os
        v = sys.version_info
        curr_ver = f"{v.major}.{v.minor}"
        acqu_ver = os.environ['PYTHON_VERSION']
        assert curr_ver == acqu_ver, "setup is incomplete"
      shell: python
      env:
        PYTHON_VERSION: ${{ inputs.python-version }}

    - name: Install pipx
      run: python -m pip install pipx
      shell: bash
